<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'AbstractPriceDescription' => $vendorDir . '/blesta/pricing/src/Description/AbstractPriceDescription.php',
    'AbstractPriceModifier' => $vendorDir . '/blesta/pricing/src/Modifier/AbstractPriceModifier.php',
    'AutoloadPricing' => $vendorDir . '/blesta/pricing/src/AutoloadPricing.php',
    'AutoloadProration' => $vendorDir . '/blesta/proration/src/AutoloadProration.php',
    'DiscountPrice' => $vendorDir . '/blesta/pricing/src/Modifier/DiscountPrice.php',
    'ItemPrice' => $vendorDir . '/blesta/pricing/src/Type/ItemPrice.php',
    'ItemPriceCollection' => $vendorDir . '/blesta/pricing/src/Collection/ItemPriceCollection.php',
    'PriceDescriptionInterface' => $vendorDir . '/blesta/pricing/src/Description/PriceDescriptionInterface.php',
    'PriceModifierInterface' => $vendorDir . '/blesta/pricing/src/Modifier/PriceModifierInterface.php',
    'PriceTotalInterface' => $vendorDir . '/blesta/pricing/src/Total/PriceTotalInterface.php',
    'PricingFactory' => $vendorDir . '/blesta/pricing/src/PricingFactory.php',
    'Proration' => $vendorDir . '/blesta/proration/src/Proration.php',
    'TaxPrice' => $vendorDir . '/blesta/pricing/src/Modifier/TaxPrice.php',
    'UnitPrice' => $vendorDir . '/blesta/pricing/src/Type/UnitPrice.php',
);
