<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaa88b96a66677513ea5f2a117b3b9406
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
        'B' => 
        array (
            'Blesta\\Composer\\Installer\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
        'Blesta\\Composer\\Installer\\' => 
        array (
            0 => __DIR__ . '/..' . '/blesta/composer-installer/src',
        ),
    );

    public static $classMap = array (
        'AbstractPriceDescription' => __DIR__ . '/..' . '/blesta/pricing/src/Description/AbstractPriceDescription.php',
        'AbstractPriceModifier' => __DIR__ . '/..' . '/blesta/pricing/src/Modifier/AbstractPriceModifier.php',
        'AutoloadPricing' => __DIR__ . '/..' . '/blesta/pricing/src/AutoloadPricing.php',
        'AutoloadProration' => __DIR__ . '/..' . '/blesta/proration/src/AutoloadProration.php',
        'DiscountPrice' => __DIR__ . '/..' . '/blesta/pricing/src/Modifier/DiscountPrice.php',
        'ItemPrice' => __DIR__ . '/..' . '/blesta/pricing/src/Type/ItemPrice.php',
        'ItemPriceCollection' => __DIR__ . '/..' . '/blesta/pricing/src/Collection/ItemPriceCollection.php',
        'PriceDescriptionInterface' => __DIR__ . '/..' . '/blesta/pricing/src/Description/PriceDescriptionInterface.php',
        'PriceModifierInterface' => __DIR__ . '/..' . '/blesta/pricing/src/Modifier/PriceModifierInterface.php',
        'PriceTotalInterface' => __DIR__ . '/..' . '/blesta/pricing/src/Total/PriceTotalInterface.php',
        'PricingFactory' => __DIR__ . '/..' . '/blesta/pricing/src/PricingFactory.php',
        'Proration' => __DIR__ . '/..' . '/blesta/proration/src/Proration.php',
        'TaxPrice' => __DIR__ . '/..' . '/blesta/pricing/src/Modifier/TaxPrice.php',
        'UnitPrice' => __DIR__ . '/..' . '/blesta/pricing/src/Type/UnitPrice.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaa88b96a66677513ea5f2a117b3b9406::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaa88b96a66677513ea5f2a117b3b9406::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitaa88b96a66677513ea5f2a117b3b9406::$classMap;

        }, null, ClassLoader::class);
    }
}
